### ISSUE TITLE
[Feature]: Manage sounds on the game and control the volume

### ISSUE THREAD

**Issue by jvondermarck** [jvondermarck/dinosaur-exploder#76] opened 2022-07-10 14:52 UTC
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate features.

### 😍 Describe the solution you'd like

It would be great to have a button on the home screen to put the sound of the game on or off.
![image](https://user-images.githubusercontent.com/62793491/178149956-0d602870-f212-4ca1-a11a-565137b55706.png)

### 👍️ Describe alternatives you've considered

It would be great maybe to have a gauge, to increase or decrease the intensity of the sound?

**Comment by RamonASV** [comment] 2022-07-11 01:34
Hello! May I work on this issue? I already have an idea on how to work this out.

**Comment by jvondermarck** [comment] 2022-07-11 05:08
Hi @RamonASV yeah of course, go ahead :)

**Comment by RamonASV** [comment] 2022-07-11 23:36
I'm currently having some troubles on this, as DinosaurController.java uses FXGL.play() instead of a MediaPlayer. As of now I can only mute the music in the main menu. I also noticed that when you lose and return to the Main Menu the gameBackground.wav file keeps playing instead of the mainMenu.wav

**Comment by jvondermarck** [comment] 2022-07-12 04:52
For the first issue, maybe you can create a boolean variable for the music to know if the game has to put the home screen sound and the game sounds while playing, try to do that maybe?

```
if (game.isMusicOn){ play.music(engine.wav;}
```

(the code is false but it's just an example)

**Comment by jvondermarck** [comment] 2022-07-12 04:54
and for the second issue indeed something is going wrong.. that's weird.. Maybe there is a method from FXGL to stop all sounds activated and then you can activate the home screen sound again when u go back to the menu?

**Comment by Vishrut19** [comment] 2022-09-03 05:25
@RamonASV can I help you out with it ?

**Comment by jvondermarck** [comment] 2022-09-03 09:39
Hi @Vishrut19 you can finish this issue alone, I am not sure he's still working on it, so go ahead :)

**Comment by Vishrut19** [comment] 2022-09-03 09:45
> Hi @Vishrut19 you can finish this issue alone, I am not sure he's still working on it, so go ahead :)

Okay I will try to do whatever I can.

**Comment by YesShubham01** [comment] 2022-12-06 12:48
Hey, is this issue closed? , If not i would like to work on it.

**Comment by jvondermarck** [comment] 2022-12-06 20:14
@YesShubham01 Heyy, you still can work on it :)

**Comment by Anshul439** [comment] 2023-05-01 19:06
Hey, is the issue solved? If not, can you assign it to me?

**Comment by jvondermarck** [comment] 2023-05-01 21:47
Hi @Anshul439 this issue is all yours ! You can work on it !

**Comment by Anshul439** [comment] 2023-05-04 10:28
Hey! I have made a PR. Please check it out and let me know if the problem is solved.

**Comment by jvondermarck** [comment] 2024-04-18 19:28
Now it would be better to also control the volume.

**Comment by alemarin5** [comment] 2024-08-06 22:11
Hi, can I work on this issue?

**Comment by jvondermarck** [comment] 2024-08-07 05:44
> Hi, can I work on this issue?

Heyy, @alemarin5 absolutely you can work on it !

**Closed as completed** 2024-08-26 20:04 UTC
Labels: good first issue, difficulty: medium
